2024-01-08 15:41:09,906 [__main__:INFO] [main.py <19>: main.<module>] Logger successfully installed
2024-01-08 15:41:09,907 [__main__:INFO] [main.py <20>: main.<module>] Starting bot
2024-01-08 15:41:11,719 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=788207542
2024-01-08 15:41:11,719 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=788207542
2024-01-08 15:41:14,194 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=788207542 user_input=—топ, correct=локт≈й
2024-01-08 15:41:14,215 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=788207542
2024-01-08 15:41:14,215 [__main__:DEBUG] [main.py <28>: main.start] Connected to datebase(base) for userid=788207542
2024-01-08 15:41:14,215 [__main__:DEBUG] [main.py <38>: main.start] Connection to database(base): restarting bot for userid=788207542
